ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Controllers/PatientsController.cs
using Microsoft.Ajax.Utilities;
using PagedList;
using Project_MVC_Work_001.Models;
using Project_MVC_Work_001.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlTypes;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_MVC_Work_001.Controllers
{
    public class PatientsController : Controller
    {
        private readonly HospitalDbContext db=new HospitalDbContext();
        // GET: Patients
        public ActionResult Index()
        {
            return View(db.Patients.ToList());
        }
        public PartialViewResult patientInformation(int pg = 1)
        {
            var data = db.Patients
                     .Include(x => x.PatientDetails)
                     .Include(x => x.Department)
                     .Include(x => x.Doctor)
                     .OrderBy(x => x.PatientId)
                     .ToPagedList(pg, 5);
            return PartialView("_patientInformation",data);
                     
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult CreateForm()
        {
            PatientInputModel model = new PatientInputModel();
            model.PatientDetails.Add(new PatientDetails());
            ViewBag.Doctor=db.Doctors.ToList();
            ViewBag.Department=db.Departments.ToList();
            return PartialView("_CreateForm",model);
        }
        [HttpPost]
        public ActionResult Create(PatientInputModel model,string act="")
        {
            if (act == "add")
            {
                model.PatientDetails.Add(new PatientDetails());
                foreach (var item in ModelState.Values)
                {
                    item.Errors.Clear();
                    item.Value = null;
                }

            }
            if(act =="remove")
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                model.PatientDetails.RemoveAt(index);
                foreach (var item in ModelState.Values)
                {
                    item.Errors.Clear();
                    item.Value = null;
                }
            }
            if(act =="insert")
            {
                if(ModelState.IsValid)
                {
                    var patient = new Patient()
                    {
                        DoctorId = model.DoctorId,
                        DepatmentId=model.DepatmentId,
                        PatientName=model.PatientName,
                        AdmissioneDate=model.AdmissioneDate,
                        Age=model.Age,
                        MaritialStatus=model.MaritialStatus,
                    };
                    //for image
                    string ex = Path.GetExtension(model.Picture.FileName);
                    string file = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ex;
                    string savepath = Path.Combine(Server.MapPath("~/Images"), file);
                    model.Picture.SaveAs(savepath);
                    patient.Picture = file;

                    db.Patients.Add(patient);
                    db.SaveChanges();
                    //patientDetails
                    foreach (var item in model.PatientDetails)
                    {
                        db.Database.ExecuteSqlCommand($@"spInsertPatientDetails {(int)item.Test},{item.Description},{item.Cost},{patient.PatientId}");
                    }
                    PatientInputModel inputModel = new PatientInputModel()
                    {
                        PatientName="",
                        AdmissioneDate=DateTime.Today
                    };
                    inputModel.PatientDetails.Add(new PatientDetails());
                    ViewBag.Doctor=db.Doctors.ToList();
                    ViewBag.Department=db.Departments.ToList();
                    foreach (var item in ModelState.Values)
                    {
                        item.Value = null;
                    }
                    return View("_CreateForm",inputModel);
                }
            }
            ViewBag.Doctor = db.Doctors.ToList();
            ViewBag.Department = db.Departments.ToList();
            return View("_CreateForm",model);
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public ActionResult EditForm(int id)
        {
            var data =db.Patients.FirstOrDefault(x=>x.PatientId==id);
            if(data == null) return new HttpNotFoundResult();
            db.Entry(data).Collection(x=>x.PatientDetails).Load();
            PatientEditModel editModel = new PatientEditModel()
            {
                PatientId= id,
                DoctorId=data.DoctorId,
                DepatmentId=data.DepatmentId,
                PatientName=data.PatientName,
                Age=data.Age,
                AdmissioneDate=data.AdmissioneDate,
                MaritialStatus=data.MaritialStatus,
                PatientDetails=data.PatientDetails.ToList(),
            };
            ViewBag.Doctor = db.Doctors.ToList();
            ViewBag.Department = db.Departments.ToList();
            ViewBag.currentpicture = data.Picture;
            return PartialView("_EidtForm",editModel);
        }
        [HttpPost]
        public ActionResult Edit(PatientEditModel patientEdit,string act = "")
        {
            if(act == "add")
            {
                patientEdit.PatientDetails.Add(new PatientDetails());
                foreach (var item in ModelState.Values)
                {
                    item.Errors.Clear();
                    item.Value = null;
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                patientEdit.PatientDetails.RemoveAt(index);
                foreach (var item in ModelState.Values)
                {
                    item.Errors.Clear();
                    item.Value = null;
                }
            }
            if (act == "update")
            {
                if(ModelState.IsValid)
                {
                    var patient = db.Patients.FirstOrDefault(x => x.PatientId == patientEdit.PatientId);
                    if (patient == null) { return new HttpNotFoundResult(); }
                    patient.PatientName = patientEdit.PatientName;
                    patient.Age = patientEdit.Age;
                    patient.AdmissioneDate = patientEdit.AdmissioneDate;
                    patient.MaritialStatus = patientEdit.MaritialStatus;
                    patient.DoctorId = patientEdit.DoctorId;
                    patient.DepatmentId = patientEdit.DepatmentId;
                    if (patientEdit.Picture != null)
                    {
                        string str = Path.GetExtension(patientEdit.Picture.FileName);
                        string file = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + str;
                        string savepath = Path.Combine(Server.MapPath("~/Images"), file);
                        patientEdit.Picture.SaveAs(savepath);
                        patient.Picture = file;
                    }
                    else
                    {

                    }
                    db.SaveChanges();
                    db.Database.ExecuteSqlCommand($"EXEC DeletePatientDetailsByPatientId {patient.PatientId}");
                    foreach (var item in patientEdit.PatientDetails)
                    {
                        db.Database.ExecuteSqlCommand($"EXEC spInsertPatientDetails {(int)item.Test},{item.Description},{item.Cost},{patient.PatientId}");
                    }
                }
            }
            ViewBag.Doctor = db.Doctors.ToList();
            ViewBag.Department = db.Departments.ToList();
            ViewBag.currentpicture = db.Patients.FirstOrDefault(x => x.PatientId == patientEdit.PatientId)?.Picture;
            return View("_EidtForm",patientEdit);
        } 
        public ActionResult Delete(int id)
        {
            var patient = db.Patients.Find(id);
            if(patient != null)
            {
                var delete=db.PatientDetails.Where(x=>x.PatientId==id).ToList(); 
                db.PatientDetails.RemoveRange(delete);
                db.Patients.Remove(patient);
                db.SaveChanges();
                TempData["DeleteMessage"] = "Patient Delete Successfully!!!";
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult pagination(string name="")
        {
            List<Patient> modeldata;
            if(string.IsNullOrEmpty(name))
                modeldata=db.Patients.ToList();
            else
                modeldata=db.Patients.Where(n=>n.PatientName.ToLower().Equals(name.ToLower())).ToList();
            return PartialView("_Page", modeldata);
        }
    }
}

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Patients/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col">
        <div id="form">
            @Html.Action("CreateForm")
        </div>
    </div>
</div>

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Patients/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Patients/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2 class="display-4">Edit Patient</h2>
<div class="row">
    <div class="col">
        <div id="form">
            @Html.Action("EditForm")
        </div>
    </div>
</div>

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Patients/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2 class="display-4">Patient List</h2>
<div class="row">
    <div class="col">
        <div class="d-flex justify-content-end">
            <a href="@Url.Action("Create","Patients")" class="btn btn-outline-primary btn-sm"><i class="fa fa-plus-circle"></i> Add New Patient</a>
        </div>
        <div id="table">
            @Html.Action("patientInformation")
        </div>
    </div>
</div>


@section scripts{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <script>
        $(document).on("click", "button.show", function () {
            var showbtn = $(this);
            var hidebtn = showbtn.next();
            var trsh = showbtn.closest("tr");
            var trst = trsh.next();
            showbtn.hide();
            hidebtn.show();
            trst.show();
        });
        $(document).on("click", "button.hide", function () {
            var hidebtn = $(this);
            var showbtn = hidebtn.prev();
            var trsh = showbtn.closest("tr");
            var trst = trsh.next();
            showbtn.show();
            hidebtn.hide();
            trst.hide();
        });
    </script>
}

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Patients/_CreateForm.cshtml
@model Project_MVC_Work_001.Models.ViewModels.PatientInputModel

@using (Ajax.BeginForm("Create", "Patients", new { }, new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "form",
    OnSuccess = "OnSuccess"
}, new { id = "frm", enctype = "multipart/form-data" }))
{
    <h2 class="display-4">Add New Patient</h2>
    <div class="row mb-2">
        @Html.LabelFor(x => x.DoctorId, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.DropDownListFor(x => x.DoctorId, new SelectList(ViewBag.Doctor, "DoctorId", "DoctorName"), "----select-----", new { @class = "form-select" })
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.DoctorId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.DepatmentId, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.DropDownListFor(x => x.DepatmentId, new SelectList(ViewBag.Department, "DepartmentId", "DepartmentName"), "----select-----", new { @class = "form-select" })
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.DepatmentId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.PatientName, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.TextBoxFor(x => x.PatientName, new { @class = "form-control" })
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.PatientName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Age, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.TextBoxFor(x => x.Age, new { @class = "form-control" })
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.Age, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.AdmissioneDate, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.TextBoxFor(x => x.AdmissioneDate, new { @class = "form-control", type = "date" })
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.AdmissioneDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.MaritialStatus, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.CheckBoxFor(x => x.MaritialStatus)
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.MaritialStatus, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        <div class="col">
            <div class="d-flex justify-content-between">
                <h3 class="display-4">Patientdetails</h3>
                <button class="btn btn-success btn-sm mb-2" type="submit" name="act" value="add" formnovalidate><i class="fa fa-plus-circle"></i></button>
            </div>
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th>Test</th>
                        <th>Description</th>
                        <th>Cost</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.PatientDetails.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.EnumDropDownListFor(x => Model.PatientDetails[i].Test, new { @class = "form-select" })
                                @Html.ValidationMessageFor(x => Model.PatientDetails[i].Test, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.PatientDetails[i].Description, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.PatientDetails[i].Description, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.PatientDetails[i].Cost, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.PatientDetails[i].Cost, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                <button name="act" value="remove_@i" type="submit" class="btn btn-danger btn-sm" formnovalidate>Remove</button>
                            </td>
                        </tr>
                     }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-6">
            <button type="submit" name="act" value="insert" class="btn btn-primary">Save</button>
        </div>
    </div>
}

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Patients/_EidtForm.cshtml
@model Project_MVC_Work_001.Models.ViewModels.PatientEditModel

@using (Ajax.BeginForm("Edit", "Patients", new { }, new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "form",
    OnSuccess = "OnSuccess"
}, new { id = "frm", enctype = "multipart/form-data" }))
{
    <h2 class="display-4">Edit Patient</h2>
    <div class="row mb-2">
        @Html.HiddenFor(x=>x.PatientId)
        @Html.HiddenFor(x=>x.Picture)
        @Html.LabelFor(x => x.DoctorId, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.DropDownListFor(x => x.DoctorId, new SelectList(ViewBag.Doctor, "DoctorId", "DoctorName"), "----select-----", new { @class = "form-select" })
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.DoctorId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.DepatmentId, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.DropDownListFor(x => x.DepatmentId, new SelectList(ViewBag.Department, "DepartmentId", "DepartmentName"), "----select-----", new { @class = "form-select" })
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.DepatmentId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.PatientName, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.TextBoxFor(x => x.PatientName, new { @class = "form-control" })
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.PatientName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Age, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.TextBoxFor(x => x.Age, new { @class = "form-control" })
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.Age, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.AdmissioneDate, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.TextBoxFor(x => x.AdmissioneDate, new { @class = "form-control", type = "date" })
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.AdmissioneDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.MaritialStatus, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.CheckBoxFor(x => x.MaritialStatus)
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.MaritialStatus, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2" })
        <div class="col-8">
            @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
            <img src="~/Images/@ViewBag.currentpicture" style="width:35px;" class="img-thumbnail" />
        </div>
        <div class="col-2">
            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-2">
        <div class="col">
            <div class="d-flex justify-content-between">
                <h3 class="display-4">Patientdetails</h3>
                <button class="btn btn-success btn-sm mb-2" type="submit" name="act" value="add" formnovalidate><i class="fa fa-plus-circle"></i></button>
            </div>
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th>Test</th>
                        <th>Description</th>
                        <th>Cost</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.PatientDetails.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.EnumDropDownListFor(x => Model.PatientDetails[i].Test, new { @class = "form-select" })
                                @Html.ValidationMessageFor(x => Model.PatientDetails[i].Test, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.PatientDetails[i].Description, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.PatientDetails[i].Description, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.PatientDetails[i].Cost, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.PatientDetails[i].Cost, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                <button name="act" value="remove_@i" type="submit" class="btn btn-danger btn-sm" formnovalidate>Remove</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-6">
            <button type="submit" name="act" value="update" class="btn btn-primary">Update</button>
        </div>
    </div>
}

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Patients/_Page.cshtml
@model IEnumerable<Project_MVC_Work_001.Models.Patient>
    
<table class="table table-bordered table-striped table-sm">
    <thead class="table-info">
        <tr>
            <th>@Html.DisplayNameFor(x => x.PatientName)</th>
            <th>@Html.DisplayNameFor(x => x.Age)</th>
            <th>@Html.DisplayNameFor(x => x.AdmissioneDate)</th>
            <th>@Html.DisplayNameFor(x => x.MaritialStatus)</th>
            <th>@Html.DisplayNameFor(x => x.Picture)</th>
        </tr>
    </thead>
    <tbody >
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(x => item.PatientName)</td>
                <td>@Html.DisplayFor(x => item.Age)</td>
                <td>@Html.DisplayFor(x => item.AdmissioneDate)</td>
                <td>@Html.DisplayFor(x => item.MaritialStatus)</td>
                <td>@Html.DisplayFor(x => item.Picture)</td>
            </tr>
        }
    </tbody>
</table>

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Patients/_patientInformation.cshtml
@model IEnumerable<Project_MVC_Work_001.Models.Patient>
@using PagedList
@using PagedList.Mvc

<table class="table table-bordered table-striped table-sm">
    <thead class="table-primary">
        <tr>
            <th>Show Details</th>
            <th>Picture</th>
            <th>Patient Name</th>
            <th>Age</th>
            <th>Admission Date</th>
            <th>Doctor</th>
            <th>Department</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="width:40px;text-align:center">
                    <button type="button" class="btn btn-sm show">Show</button>
                    <button type="button" class="btn btn-sm hide" style="display:none">Hide</button>
                </td>
                <td style="width:50px; text-align:center">
                    <img src="~/Images/@item.Picture" class="rounded-circle" style="width:32px" />
                </td>
                <td>@item.PatientName</td>
                <td>@item.Age</td>
                <td>@item.AdmissioneDate.ToString("yyyy-MM-dd")</td>
                <td>@item.Doctor.DoctorName</td>
                <td>@item.Department.DepartmentName</td>
                <td>
                    <a href="@Url.Action("Edit", "Patients", new { id = item.PatientId })" class="btn btn-success"><i class="fa fa-pencil"></i></a>
                    <a href="@Url.Action("Delete", "Patients", new { id = item.PatientId })" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
            <tr style="display:none">
                <td></td>
                <td colspan="6">
                    <h2 class="display-4">PatientDetails</h2>
                    <table class="table table-bordered table-sm table-striped">
                        <thead class="table-info">
                            <tr>
                                <th>Test</th>
                                <th>Description</th>
                                <th>Cost</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var pd in item.PatientDetails)
                            {
                                <tr>
                                    <td>@pd.Test</td>
                                    <td>@pd.Description</td>
                                    <td>@pd.Cost</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </td>
            </tr>
        }
    </tbody>   
</table>