ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_MVC_Work_001.Models;

namespace Project_MVC_Work_001.Controllers
{
    public class DoctorsController : Controller
    {
        private HospitalDbContext db = new HospitalDbContext();
        public ActionResult Index()
        {
            return View(db.Doctors.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DoctorId,DoctorName")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DoctorId,DoctorName")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Doctors/Create.cshtml
@model Project_MVC_Work_001.Models.Doctor

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div >
        <h4 class="display-4">Doctor</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DoctorName, htmlAttributes: new { @class = "control-label col-md-2 col-6" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.DoctorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DoctorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Doctors/Delete.cshtml
@model Project_MVC_Work_001.Models.Doctor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Doctors/Details.cshtml
@model Project_MVC_Work_001.Models.Doctor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DoctorId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Doctors/Edit.cshtml
@model Project_MVC_Work_001.Models.Doctor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Doctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DoctorId)

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoctorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DoctorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Doctors/Index.cshtml
@model IEnumerable<Project_MVC_Work_001.Models.Doctor>

@{
    ViewBag.Title = "Index";
}

<h2 class="display-4">Doctor List</h2>
<div class="d-flex justify-content-between">
    <a href="@Url.Action("Create","Doctors")" class="btn btn-success btn-sm mb-2"><i class="fa fa-plus-circle"></i> Add New Doctor</a>
</div>

<table class="table table-bordered table-striped table-info table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DoctorName)
        </th>
        <th>Action</th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DoctorName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DoctorId }, new {@class="btn btn-success btn-sm"})
            @Html.ActionLink("Delete", "Delete", new { id=item.DoctorId }, new {@class="btn btn-danger btn-sm"})
        </td>
    </tr>
}

</table>