ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_MVC_Work_001.Models;

namespace Project_MVC_Work_001.Controllers
{
    public class DepartmentsController : Controller
    {
        private HospitalDbContext db = new HospitalDbContext();

        public ActionResult Index()
        {
            return View(db.Departments.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmentId,DepartmentName")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(department);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DepartmentId,DepartmentName")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Department department = db.Departments.Find(id);
            db.Departments.Remove(department);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Departments/Create.cshtml
@model Project_MVC_Work_001.Models.Department

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input  type="submit" value="Create" class="btn btn-success mt-2" />
            </div>
        </div>
    </div>
}

<div >
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Departments/Delete.cshtml
@model Project_MVC_Work_001.Models.Department

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Department</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Departments/Details.cshtml
@model Project_MVC_Work_001.Models.Department

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Department</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DepartmentId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Departments/Edit.cshtml
@model Project_MVC_Work_001.Models.Department

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DepartmentId)

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ESAD_CS_PROJECT_HOSPITAL_MANAGEMENT/Project_MVC_Work_001/Views/Departments/Index.cshtml
@model IEnumerable<Project_MVC_Work_001.Models.Department>

@{
    ViewBag.Title = "Index";
}

<h2 class="display-4">Department List</h2>

<div class="d-flex justify-content-between">
    <a href="@Url.Action("Create","Departments")" class="btn btn-success btn-sm mb-2"><i class="fa fa-plus-circle"></i> Add New Department</a>
</div>
<table class="table table-bordered table-striped table-sm">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DepartmentName)
        </th>
        <th>Action</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DepartmentName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.DepartmentId }, new { @class = "btn btn-success btn-sm" })
            @Html.ActionLink("Delete", "Delete", new { id = item.DepartmentId }, new { @class = "btn btn-danger btn-sm" })
        </td>
    </tr>
}

</table>